# suppress inspection "UnusedProperty" for whole file
server.port=8080
spring.application.name=fision-service-apps
spring.main.allow-circular-references=true

#Local Gilang
# Primary Database Configuration
spring.datasource.primary.jdbc-url=jdbc:mysql://localhost:2222/fision
spring.datasource.primary.username=fision
spring.datasource.primary.password=3xP#9qL!Vz@8Tf
spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.primary.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.primary.hibernate.ddl-auto=update

# Secondary Database Configuration
spring.datasource.secondary.jdbc-url=jdbc:mysql://localhost:2222/fision-outsource
spring.datasource.secondary.username=fision
spring.datasource.secondary.password=3xP#9qL!Vz@8Tf
spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.secondary.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Primary Database Configuration
#spring.datasource.primary.jdbc-url=jdbc:mysql://103.118.101.163:3306/fision?useUnicode=true
#spring.datasource.primary.username=fision
#spring.datasource.primary.password=3xP#9qL!Vz@8Tf
#spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.primary.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Secondary Database Configuration
#spring.datasource.secondary.jdbc-url=jdbc:mysql://localhost:3306/fision-outsource?useUnicode=true
#spring.datasource.secondary.username=fision
#spring.datasource.secondary.password=3xP#9qL!Vz@8Tf
#spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.secondary.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Database Monap
#spring.datasource.secondary.jdbc-url=jdbc:mysql://hka.cubicloud.id:6033/monap_hka?useUnicode=true&serverTimezone=Asia/Jakarta
#spring.datasource.secondary.username=fision_monap
#spring.datasource.secondary.password=hdTxH0GH__3qXprg
#spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.secondary.hibernate.dialect=org.hibernate.dialect.MySQLDialec

#Dev Cloud
# Primary Database Configuration
#spring.datasource.primary.jdbc-url=jdbc:mysql://10.8.0.1:3306/fision?useUnicode=true
#spring.datasource.primary.username=fision
#spring.datasource.primary.password=Y0urthr1fty@s5
#spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.primary.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Secondary Database Configuration
#spring.datasource.secondary.jdbc-url=jdbc:mysql://10.8.0.1:3306/fision-outsource?useUnicode=true
#spring.datasource.secondary.username=fision
#spring.datasource.secondary.password=Y0urthr1fty@s5
#spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.secondary.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=fision2024
jwt.validity=3600

#AesEncodeDecode
secret.key=!tur4h4si4d0n6y4

# SMTP Server
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lorddev.comp@gmail.com
spring.mail.password=pjqi eblj tyxm kqgh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

contract.code.prefix=HK-CC-
document.cash.out.prefix=HK-CO-

# Enable CORS for all paths with default settings
spring.webmvc.cors.allowed-origins=http://localhost:4200
spring.webmvc.cors.allowed-methods=GET,POST,PUT,DELETE
spring.webmvc.cors.allowed-headers=*
spring.webmvc.cors.allow-credentials=true

#file path
file.path=src/main/resources/

#Synchronize Config
batch.data.count=500



