# suppress inspection "UnusedProperty" for whole file
server.port=8080
spring.application.name=fision-service-apps
spring.main.allow-circular-references=true

#Dev
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://103.183.75.112:3306/fision?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Jakarta&useLegacyDatetimeCode=false
spring.datasource.username=root
spring.datasource.password=LILbear@08

jwt.secret=fision2024
jwt.validity=3600

#AesEncodeDecode
secret.key=!tur4h4si4d0n6y4

spring.mail.host=smtp.mailgun.org
spring.mail.port=587
spring.mail.username=postmaster@sandboxa535174927d14491b3b4d4be00d5fc62.mailgun.org
spring.mail.password=fe35e35aad6c12a50112e16ffe701784-324e0bb2-5365e9bc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#password mailgun : 27VEr*VffZccnUb

contract.code.prefix=HK-CC-
document.cash.out.prefix=HK-CO-

# Enable CORS for all paths with default settings
spring.webmvc.cors.allowed-origins=http://localhost:4200,http://103.183.75.112:4200
spring.webmvc.cors.allowed-methods=GET,POST,PUT,DELETE
spring.webmvc.cors.allowed-headers=*
spring.webmvc.cors.allow-credentials=true
