server.port=8080
spring.application.name=fision-service-apps
spring.main.allow-circular-references=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://10.8.0.1:3306/fision
spring.datasource.username=fision
spring.datasource.password=Y0urthr1fty@s5
jwt.secret=fision2024
jwt.validity=3600
secret.key=!tur4h4si4d0n6y4
contract.code.prefix=HK-CC-
document.cash.out.prefix=HK-CO-
spring.webmvc.cors.allowed-origins=http://localhost:4200,http://103.183.75.112:4200,https://yourthriftyass.my.id
spring.webmvc.cors.allowed-methods=GET,POST,PUT,DELETE
spring.webmvc.cors.allowed-headers=*
spring.webmvc.cors.allow-credentials=true
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/api-spec.yml
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lorddev.comp@gmail.com
spring.mail.password=pjqi eblj tyxm kqgh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.main.headless=true
spring.jackson.time-zone=GMT+7
file.path=src/main/resources/